#!/usr/bin/env bash
# apple-efi-setup.sh — Set up Xen EFI boot on Apple hardware
#
# Apple's EFI firmware ignores named EFI boot entries created by grub-install
# on the first boot. This script installs xen.efi as the fallback EFI binary
# (EFI/BOOT/BOOTx64.EFI) so Apple firmware loads it unconditionally.
#
# Two boot paths are configured:
#   Primary:  /boot/efi/EFI/BOOT/BOOTx64.EFI  (Apple EFI fallback — xen.efi)
#   Secondary: /boot/efi/EFI/qubentoo/grubx64.efi (GRUB, chainloaded by xen.efi)
#
# xen.efi reads /boot/efi/EFI/BOOT/xen.cfg which specifies the kernel + initramfs.
#
# Usage (run as root after bootstrap-dom0.sh):
#   bash scripts/apple-efi-setup.sh [--efi-dir /boot/efi] [--xen-version 4.17.5]

set -euo pipefail

EFI_DIR="${EFI_DIR:-/boot/efi}"
XEN_VERSION="${XEN_VERSION:-4.17.5}"
DOM0_MEM_MB="${DOM0_MEM_MB:-4096}"
OVERLAY_SRC="${OVERLAY_SRC:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BOLD='\033[1m'; RESET='\033[0m'
info()  { printf "${GREEN}>>> %s${RESET}\n" "$*"; }
warn()  { printf "${YELLOW}!!! %s${RESET}\n" "$*"; }
die()   { printf "${RED}ERROR: %s${RESET}\n" "$*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Must be run as root."

# --- argument parsing ---------------------------------------------------

while [[ $# -gt 0 ]]; do
    case "$1" in
        --efi-dir)     EFI_DIR="$2";     shift 2 ;;
        --xen-version) XEN_VERSION="$2"; shift 2 ;;
        --dom0-mem)    DOM0_MEM_MB="$2"; shift 2 ;;
        *) die "Unknown option: $1" ;;
    esac
done

EFI_BOOT_DIR="${EFI_DIR}/EFI/BOOT"
EFI_QUBENTOO_DIR="${EFI_DIR}/EFI/qubentoo"

# --- sanity checks ------------------------------------------------------

[[ -d "${EFI_DIR}" ]] || die "${EFI_DIR} is not mounted. Mount the EFI partition first."

XEN_EFI_SRC="/usr/lib/xen/boot/xen.efi"
[[ -f "${XEN_EFI_SRC}" ]] || die "xen.efi not found at ${XEN_EFI_SRC}. Emerge app-emulation/xen first."

# Locate kernel and initramfs
KERNEL=$(find /boot -maxdepth 1 -name "vmlinuz*" 2>/dev/null | sort -V | tail -1)
INITRAMFS=$(find /boot -maxdepth 1 \( -name "initramfs*" -o -name "initrd*" \) 2>/dev/null | sort -V | tail -1)

[[ -n "${KERNEL}" ]]    || die "No kernel image found in /boot. Build/install the kernel first."
[[ -n "${INITRAMFS}" ]] || warn "No initramfs found — proceeding, but dom0 may fail to boot without one."

KERNEL_BASE="$(basename "${KERNEL}")"
INITRAMFS_BASE="$(basename "${INITRAMFS:-}")"

# --- step 1: install xen.efi as EFI fallback ----------------------------

info "Installing xen.efi as Apple EFI fallback binary..."
mkdir -p "${EFI_BOOT_DIR}" "${EFI_QUBENTOO_DIR}"

cp -v "${XEN_EFI_SRC}" "${EFI_BOOT_DIR}/BOOTx64.EFI"
cp -v "${XEN_EFI_SRC}" "${EFI_QUBENTOO_DIR}/xen.efi"
info "xen.efi installed to ${EFI_BOOT_DIR}/BOOTx64.EFI"

# --- step 2: copy kernel and initramfs into EFI partition ---------------
# xen.efi reads modules relative to the EFI partition, so kernel + initramfs
# must be accessible from the EFI partition or via full path.

info "Copying kernel and initramfs into EFI partition..."
cp -v "${KERNEL}" "${EFI_QUBENTOO_DIR}/${KERNEL_BASE}"
[[ -n "${INITRAMFS_BASE}" ]] && cp -v "${INITRAMFS}" "${EFI_QUBENTOO_DIR}/${INITRAMFS_BASE}"
info "Kernel and initramfs copied."

# Determine root partition UUID for kernel cmdline
ROOT_DEV=$(findmnt -n -o SOURCE / 2>/dev/null || mount | awk '$3=="/" {print $1}' | head -1)
ROOT_UUID=$(blkid -s UUID -o value "${ROOT_DEV}" 2>/dev/null || true)
ROOT_ARG="${ROOT_UUID:+root=UUID=${ROOT_UUID}}"
ROOT_ARG="${ROOT_ARG:-root=${ROOT_DEV}}"

# --- step 3: write xen.cfg ----------------------------------------------

CFG_FILE="${EFI_BOOT_DIR}/xen.cfg"
info "Writing ${CFG_FILE}..."

cat > "${CFG_FILE}" << EOF
# Xen EFI boot configuration — generated by apple-efi-setup.sh
# Edit this file to change kernel parameters or add boot entries.
# xen.cfg format: https://xenbits.xen.org/docs/4.17-testing/misc/efi.html

[global]
default=qubentoo
timeout=5

[qubentoo]
options=dom0_mem=${DOM0_MEM_MB}M,max:${DOM0_MEM_MB}M dom0_max_vcpus=4 iommu=on dom0_vcpus_pin console=vga,com1 com1=115200,8n1
kernel=/EFI/qubentoo/${KERNEL_BASE} ${ROOT_ARG} ro quiet intel_iommu=on applesmc.power=1
$([ -n "${INITRAMFS_BASE}" ] && echo "ramdisk=/EFI/qubentoo/${INITRAMFS_BASE}")
EOF

info "xen.cfg written."

# --- step 4: also write a copy of xen.cfg next to BOOTx64.EFI ----------
# Some Apple firmware looks for xen.cfg in the same directory as the EFI binary.
cp "${CFG_FILE}" "${EFI_BOOT_DIR}/xen.cfg"

# --- step 5: optional efibootmgr entry ----------------------------------

if command -v efibootmgr >/dev/null 2>&1; then
    info "Adding EFI boot entry via efibootmgr..."
    # Detect EFI disk and partition number
    EFI_PART_DEV=$(findmnt -n -o SOURCE "${EFI_DIR}" 2>/dev/null | head -1)
    if [[ -n "${EFI_PART_DEV}" ]]; then
        EFI_DISK=$(echo "${EFI_PART_DEV}" | sed 's/p\?[0-9]*$//')
        EFI_PARTNUM=$(echo "${EFI_PART_DEV}" | grep -oP '[0-9]+$')
        efibootmgr \
            --create \
            --disk "${EFI_DISK}" \
            --part "${EFI_PARTNUM}" \
            --label "Qubentoo (Xen ${XEN_VERSION})" \
            --loader "\\EFI\\BOOT\\BOOTx64.EFI" \
            || warn "efibootmgr failed — Apple firmware will still use EFI/BOOT/BOOTx64.EFI as fallback"
    else
        warn "Could not determine EFI partition device — skipping efibootmgr"
    fi
else
    warn "efibootmgr not found — skipping boot entry creation"
    warn "Apple firmware will use /EFI/BOOT/BOOTx64.EFI automatically as fallback."
fi

# --- done ---------------------------------------------------------------

printf "\n${GREEN}${BOLD}Apple EFI boot setup complete.${RESET}\n"
printf "\nBoot path: Apple EFI → ${EFI_BOOT_DIR}/BOOTx64.EFI (xen.efi)\n"
printf "           → reads: ${CFG_FILE}\n"
printf "           → loads: /EFI/qubentoo/${KERNEL_BASE}\n"
[[ -n "${INITRAMFS_BASE}" ]] && printf "           → ramdisk: /EFI/qubentoo/${INITRAMFS_BASE}\n"
printf "\nTo update after a kernel upgrade, re-run this script.\n"
printf "To change Xen/dom0 parameters, edit %s\n\n" "${CFG_FILE}"
